include = ["pyproject.toml", "src/**/*.py"]
exclude = []
src = ["src"]

[format]
docstring-code-format = false
[lint]
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "I"]
ignore = []

[lint.isort]
combine-as-imports = true
force-wrap-aliases = false
known-first-party = ["powerplant"]
lines-after-imports = -1
relative-imports-order = "furthest-to-closest"
sections = { django = ["django"] }
section-order = [
    "future",
    "standard-library",
    "django",
    "third-party",
    "first-party",
    "local-folder",
]